server {
    listen 80;

    # Raíz de los archivos estáticos del frontend
    root /usr/share/nginx/html;
    index index.html;

    # Cualquier ruta que no sea /api/ la resuelve como archivo estático
    location / {
        try_files $uri $uri/ =404;
    }

    # Todo lo que empiece con /api/ se reenvía al backend Flask
    # La barra al final del proxy_pass recorta el prefijo /api/
    # Ej: /api/votar → http://backend:5000/votar
    location /api/ {
        proxy_pass http://backend:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
